name: Deploy site to Walrus

on:
  push:
    branches:
      - add-github-actions-deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Node.js + Yarn 설정 (캐시 최적화)
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"  # Yarn 캐시 활성화 ✅

      # 3. sui_client 디렉토리 의존성 설치
      - name: Install Dependencies
        run: |
          cd sui_client
          yarn install --frozen-lockfile  # Yarn 사용 ✅

      # 4. 프로젝트 빌드
      - name: Build Site
        run: |
          cd sui_client
          yarn build  # Yarn 사용 ✅

      # 5. 배포
      - name: Deploy site to Walrus
        uses: zktx-io/walrus-sites-ga@v0.3.0
        with:
          site-path: "./sui_client/dist/"
          network: "testnet"
          object-id: "0xb3cb1d4980ebc68da0f1ca8e1e75d19ca273374d9f09e9d025a0b4d6a7586540"
        env:
          SUI_ADDRESS: ${{ secrets.SUI_ADDRESS }}
          SUI_KEYSTORE: ${{ secrets.SUI_KEYSTORE }}
