name: Deploy site to Walrus

on:
  workflow_dispatch:  # branches 키 삭제

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/add-github-actions-deployment'  # 브랜치 조건 추가

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: |
          cd sui_client
          pnpm install

      - name: Build Site
        run: |
          cd sui_client
          pnpm run build

      - name: List Build Directory
        run: |
          ls -la sui_client/dist/

      - name: Deploy site to Walrus
        uses: zktx-io/walrus-ga@latest
        with:
          site-path: './sui_client/dist/'
          network: 'testnet'
          object-id: '0
