name: Deploy site to Walrus

on:
  push:
    branches:
      - add-github-actions-deployment  # 현재 브랜치 푸시 시 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js + pnpm
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          package-manager: pnpm@latest  # pnpm 설치
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install  

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install Dependencies
        run: |
          cd sui_client
          pnpm install

      - name: Build Site
        run: |
          cd sui_client
          pnpm run build

      - name: List Build Directory
        run: |
          ls -la sui_client/dist/

      - name: Deploy site to Walrus
        uses: zktx-io/walrus-ga@v0.3.0  # 버전 수정
        with:
          site-path: './sui_client/dist/'
          network: 'testnet'
          object-id: '0xb3cb1d4980ebc68da0f1ca8e1e75d19ca273374d9f09e9d025a0b4d6a7586540'
        env:
          SUI_ADDRESS: ${{ secrets.SUI_ADDRESS }}
          SUI_KEYSTORE: ${{ secrets.SUI_KEYSTORE }}
